### ISSUE TITLE
__init__() takes from 3 to 4 positional arguments but 6 were given

### ISSUE THREAD

**Issue by MichaelSternNYC** [ebridges/plaid2qif#14]
I think I've followed the installation directions exactly, and yet when I try to get my access token, I get the following error:
```
[2020/07/04 01:13:04][INFO] reading credentials from file: ./plaid-credentials.json
Traceback (most recent call last):
  File "/usr/local/bin/plaid2qif", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/plaid2qif/plaid2qif.py", line 149, in main
    save_access_token(args['--institution'], args['--public-token'], args['--credentials'])
  File "/usr/local/lib/python3.7/dist-packages/plaid2qif/plaid2qif.py", line 108, in save_access_token
    client = open_client(plaid_credentials)
  File "/usr/local/lib/python3.7/dist-packages/plaid2qif/plaid2qif.py", line 139, in open_client
    suppress_warnings)
TypeError: __init__() takes from 3 to 4 positional arguments but 6 were given
```

**Comment by ebridges** [comment]
What’s the command (and arms) that you’re running that leads to that error?

**Comment by MichaelSternNYC** [comment]
` plaid2qif save-access-token --institution="chase" --public-token="public-sandbox-XXXXX-XXX-XXXX-XXXX-XXXXXXXXXX" --credentials="./plaid-credentials.json"`, Where the credentials file is seeded with information from https://dashboard.plaid.com/account/keys and the public token was extracted from the webpage returned from the example auth.html on the GitHub site and is not expired.

I wrote a trivial python program for retrieving an access token and it seems to work, so whatever is going wrong doesn't seem to be at the level of the sandbox.

My trivial code that seems to work:
```
from plaid import Client

client = Client(client_id='XXXXXXX', secret='YYYYYYYY', public_key='ZZZZZZZZZZ', environment='sandbox')

public_token='public-sandbox-XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXX'
response = client.Item.public_token.exchange(public_token)
print('response: ',response)
```
But the same public_token, clientID, etc., given to `plaid2qif` result only in a cascading error message.

**Comment by ebridges** [comment]
Hi @MichaelSternNYC thanks a lot for reporting this -- perhaps this is related to #16?

**Comment by MichaelSternNYC** [comment]
Interesting. Pretty good theory anyway. I don’t have time to test it now.
