### ISSUE TITLE
add support for new `link_token` Plaid API

### ISSUE THREAD

**Issue by jvns** [ebridges/plaid2qif#16]
I tried to use this tool (which looks like exactly what I need!), but I couldn't get it to work at all because in my Plaid dashboard I didn't have a `public_key`.

It turns out that as of July 23, 2020, Plaid accounts don't have a `public_key` anymore, just a client and a secret. They've introduced a new `link_token` system instead, which all new accounts have to use. So new Plaid accounts (created after July 23 2020) won't be able to use plaid2qif until it supports the new `link_token` flow.

Their migration guide is here: https://plaid.com/docs/upgrade-to-link-tokens/

**Comment by ebridges** [comment]
Hi! Thanks a lot for the heads up.  This depends on an older version of the `plaid-python` SDK, and it appears that in >v5 of that SDK they've added support (along with [examples here](https://github.com/plaid/quickstart/tree/master/python).

I typically use this product around the time I do my (US) taxes every year, so I'll try to integrate with that newer SDK later this year in prep for that.

**Comment by ebridges** [comment]
Hi @jvns -- gratefully @bhipple got to this and fixed this issue in PR #17 

I've been able to use it successfully, and have published [v1.3.4](https://github.com/ebridges/plaid2qif/releases/tag/v1.3.4) to PyPi.
