### ISSUE TITLE
missing "plaid2qif" executable

### ISSUE THREAD

**Issue by simonmichael** [ebridges/plaid2qif#19]
Still using plaid2qif often, thank you!

I had to reinstall it. I used today's master, and I could not figure out how to run it. README mentions a `plaid2qif` executable which seems to have gone missing. I copied one I was using before, included here FWIW:
```shell
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import re
import sys
from plaid2qif.plaid2qif import main
if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
```

**Comment by bhipple** [comment]
The executable is generated by `setup.py`:
https://github.com/ebridges/plaid2qif/blob/master/setup.py#L49-L51

You have to run the standard setuptools build and install to get it, or just `pip install plaid2qif`, as mentioned in the readme.
