### ISSUE TITLE
setup needs more explanation

### ISSUE THREAD

**Issue by simonmichael** [ebridges/plaid2qif#6]
This looks cool - thanks! I'm currently blocked on setting up Plaid authentication. Could an example of the required config file be added at https://github.com/ebridges/plaid2qif#authentication-prerequisites ? [I had installed with pip following the readme and did not yet have the source tree. PS on a mac with homebrew the command is `pip3` not pip.]

**Comment by jcrben** [comment]
I don't remember how I figured this out, but mine looks like a single JSON object like this:

```
{
  "client_id" : "<censored>",
  "public_key" : "<censored>",
  "secret" : "<censored>"
}
```

with values from https://dashboard.plaid.com/account/keys

**Comment by simonmichael** [comment]
I also struggled a bit with "Once you've succesfully linked, look in the browser's console (e.g. on Chrome use ⌘-⌥-i) and copy the public_token". This worked for me (tested in Firefox): 

1. While viewing auth.html, open the the web inspector's Network pane
2. Authenticate with your institution. If you're testing in Plaid's sandbox mode, remember to use the fake credentials `user_good`, `pass_good`
3. In the Network pane look for an XHR POST request to /create
4. Click it
5. In the sub-pane, click Response
6. Look for the `public_token` key in the response payload JSON and copy its value

**Comment by simonmichael** [comment]
An example command for downloading transactions would be helpful. In sandbox mode, the accounts are:
```
$ plaid2qif --credentials=/Users/simon/.plaid-credentials.json list-accounts --institution=WellsFargo
[2019/03/25 18:11:32][INFO] reading credentials from file: /Users/simon/.plaid-credentials.json
depository:checking	Plaid Checking	0000	wvr76N...
depository:savings	Plaid Saving	1111	5kqQX...
depository:cd	Plaid CD	2222	JJory...
credit:credit card	Plaid Credit Card	3333	kvgK...
depository:money market	Plaid Money Market	4444	l68rRlj...
brokerage:ira	Plaid IRA	5555	qvnd6B...
brokerage:401k	Plaid 401k	6666	KJgzL...
```
So I tried:
```
plaid2qif download --credentials=/Users/simon/.plaid-credentials.json --institution=WellsFargo --account='Plaid Checking'
plaid2qif download --credentials=/Users/simon/.plaid-credentials.json --institution=WellsFargo --account=depository:checking
plaid2qif download --credentials=/Users/simon/.plaid-credentials.json --institution=WellsFargo --account-id=0000
```

**Comment by simonmichael** [comment]
Something more like this would have worked (I did not expect that all options were required):
```
plaid2qif download --credentials=/Users/simon/.plaid-credentials.json --institution=WellsFargo --account='Plaid Checking' --account-type=checking  --account-id=wvr76N... --from=2019-03-01 --to=2019-03-25
```
